apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          resources:
            requests:
              memory: "150Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30036  
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: ssllvvm6/node-app:0.1
          resources:
            requests:
              memory: "1Mi"
              cpu: "80m"
            limits:
              memory: "200Mi"
              cpu: "150m"
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-db:27017/node-app"
