---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample-init-container
spec:
  parallelism: 20
  script:
    configMap:
      name: "k6-sample-load-test"
      file: "loadtest.js"
  arguments: --out influxdb=http://influxdb.default:8086/k6
