---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample-init-container
spec:
  parallelism: 4
  script:
    configMap:
      name: "k6-sample-spike-test"
      file: "spike-test.js"
  arguments: --out influxdb=http://influxdb.default:8086/k6